owner: BLNG-AI
repo: status

sites:
  - name: App
    url: https://app.blng.ai
  - name: Website
    url: https://www.blng.ai
  - name: Documentation
    url: https://docs.blng.ai
  - name: Help Center
    url: https://help.blng.ai

status-website:
  publish: true
  cname: status.blng.ai
  name: System Status
  logoUrl: https://docs.blng.ai/blng-logo.svg
  favicon: https://blng.ai/favicon.svg
  introTitle: " "
  introMessage: "This page provides real-time status for BLNG services."
  theme: light
  css: >-
    @font-face { font-display: swap; font-family: 'futura-pt'; font-style: normal; font-weight: 400; src: url('https://docs.blng.ai/fonts/FuturaPT-Book.woff2') format('woff2'); }
    @font-face { font-display: swap; font-family: 'futura-pt'; font-style: normal; font-weight: 500; src: url('https://docs.blng.ai/fonts/FuturaPT-Medium.woff2') format('woff2'); }
    @font-face { font-display: swap; font-family: 'futura-pt'; font-style: normal; font-weight: 600; src: url('https://docs.blng.ai/fonts/FuturaPT-Demi.woff2') format('woff2'); }
    *, *::before, *::after { font-family: 'futura-pt', sans-serif !important; }
    body { color: #292929 !important; font-family: 'futura-pt', sans-serif !important; font-variant-ligatures: none; background-color: #f5f5f5 !important; }
    h1, h2, h3, h4, h5 { font-weight: 400 !important; line-height: 115% !important; }
    p { line-height: 140% !important; font-size: 1.125rem !important; }
    b, strong { font-weight: 500 !important; }
    header h1 { display: none !important; }
    #sapper > footer { display: none !important; }
    nav { background: #f5f5f5 !important; border-bottom: none !important; width: 100vw !important; max-width: 100% !important; position: relative !important; left: 0 !important; right: 0 !important; box-sizing: border-box !important; padding-left: 5% !important; padding-right: 5% !important; }
    nav > div.container { max-width: 100% !important; width: 100% !important; padding-top: 1.75rem !important; padding-bottom: 1.75rem !important; }
    nav a.logo { display: flex !important; align-items: center !important; gap: 1.5rem !important; text-decoration: none !important; }
    nav a.logo img { width: 174px !important; height: 48px !important; }
    nav a.logo > div { font-size: 1.125rem !important; font-weight: 400 !important; font-style: normal !important; line-height: 1 !important; }
    article { background-color: #ffffff !important; }
    .lead { font-size: 1.125rem !important; }

i18n:
  footer: " "

notifications:
  - type: slack
    channel: "#ops-alerts"
